import React from 'react'

export default function Menu() {
  return (
    <>
    <p>MENU MENU MENU MENU MENU MENU MENU MENU</p>
    <p>MENU MENU MENU MENU MENU MENU MENU MENU</p>
    <p>MENU MENU MENU MENU MENU MENU MENU MENU</p>
    <p>MENU MENU MENU MENU MENU MENU MENU MENU</p>
    <p>MENU MENU MENU MENU MENU MENU MENU MENU</p>
    <p>MENU MENU MENU MENU MENU MENU MENU MENU</p>
    <p>MENU MENU MENU MENU MENU MENU MENU MENU</p>
    </>
  )
}
