import React from 'react'


export default function OrderOnline() {
  return (
    <>
    <p>ORDER ONLINE ORDER ONLINE ORDER ONLINE ORDER ONLINE ORDER ONLINE</p>
    <p>ORDER ONLINE ORDER ONLINE ORDER ONLINE ORDER ONLINE ORDER ONLINE</p>
    <p>ORDER ONLINE ORDER ONLINE ORDER ONLINE ORDER ONLINE ORDER ONLINE</p>
    <p>ORDER ONLINE ORDER ONLINE ORDER ONLINE ORDER ONLINE ORDER ONLINE</p>
    <p>ORDER ONLINE ORDER ONLINE ORDER ONLINE ORDER ONLINE ORDER ONLINE</p>
    <p>ORDER ONLINE ORDER ONLINE ORDER ONLINE ORDER ONLINE ORDER ONLINE</p>
    <p>ORDER ONLINE ORDER ONLINE ORDER ONLINE ORDER ONLINE ORDER ONLINE</p>
    </>
  )
}
